name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: jobsearchui-runner

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        npm install
        npm run build:prod

    - name: Deploy UI
      run: |
        cp ${GITHUB_OUTPUT} /var/www/jobsearch
  
